name:                lifx
version:             0.1.0.0
github:              "stites/lifx"
license:             BSD3
author:              "Sam Stites"
maintainer:          "fnz@fgvgrf.vb (cipher:rot13)"
copyright:           "Copyright: (c) 2018 Sam Stites"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stites/lifx#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions: LambdaCase, OverloadedStrings, DeriveGeneric, InstanceSigs, KindSignatures, NoImplicitPrelude, TypeApplications, TypeFamilies
  dependencies:
    - bytestring
    - cborg
    - containers
    - deepseq
    - network
    - resourcet
    - serialise
    - streaming
    - udp-streaming
    - unordered-containers

executables:
  lifx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lifx
    - optparse-applicative

tests:
  lifx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lifx
